pharmaR/riskassessment

Server/uploadpackage.R

Added input$upload_file to observeEvent that creates df of packages uploaded to app. When that table updates, the multi-report download button works as expected.
Closes #60

Bug fix: DT table wouldn't update when uploading multiple csv's

---

Server/db_dash_screen.R
UI/db_dash_screen.R

Clean DB Dashboard's Excel Output

---

Reports/Report_doc.Rmd
Reports/Report_html.Rmd
Server/communityusage_metrics.R
Server/cum_report.R
UI/communityusage_metrics.R
UI/cum_report.R
Utils/cum_utils.R
Utils/utils.R
app.R
global.R

Fixes #74.
PR creates a more interactive plot for users to quickly and easily choose the best x-axis timeline for viewing their package download history. Prior to writing any code, the plot used the highcharter package and looked something like this:
This PR's changelog/ to-do list:
The final plot looks like this:

Number of downloads using plotly

---

Modules/dbupload.R
Server/sidebar.R
Server/uploadpackage.R
www/main.css

- Remove duplicated call to `riskmetric:: pkg_ref` and `riskmetric::pkg_assess`.
- Detect when `export_help` is NA and display this info accordingly (before: the package `binom` for instance displayed "NA%" in green instead of "NA" in grey).
- When uploading a package, show the progress bar with the name of the package being uploaded.
- Remove system sleep time while uploading a package.

Various fixes

---

Server/communityusage_metrics.R
Server/maintenance_metrics.R
Server/testing_metrics.R

fixes WARNING message
`Warning in result_fetch(res@ptr, n = n) :
SQL statements must be issued with dbExecute() or dbSendStatement() instead of dbGetQuery() or dbSendQuery().`

Use db_ins() when INSERTing records into COMMENTS table

---

Modules/dbupload.R
Reports/Report_doc.Rmd
Reports/Report_html.Rmd
Server/db_dash_screen.R
Server/testing_metrics.R
Server/tm_report.R
Utils/sql_queries/create_TestMetrics_table.sql
Utils/sql_queries/create_metric_table.sql
Utils/sql_queries/create_package_metrics_table.sql
Utils/sql_queries/initialize_metric_table.sql
Utils/utils.R

- Created a table called `metric` to store metric information
- Created a table called `package_metrics` to store metric information per package
- Removed the `TestMetrics` table and moved the information on this table to `metric` and `package_metrics` accordingly
_Notes_: 
- The table `MaintenanceMetrics` hasn't been migrated to `metric` and `package_metrics`. Such change should be part of the next PR.
- The name `package_metrics` is not set in stone. I tried to portray that this is a one-to-many relationship (mmm although it will contain multiple packages). I'm open to suggestions =)

Created the metric and package_metrics tables, and removed the TestMetrics table

---

Server/db_dash_screen.R

Resolves issue #112 
Changes below.
Note I was able to use the CSS *order* property so it sorts on order not the background color hashtag
```{r, eval=FALSE}
colfunc <- colorRampPalette(c(low_risk_color, "gold", high_risk_color))
as.datatable(
formattable(
values$db_pkg_overview,
list(
score = formatter(
"span",
style = x ~ style(display = "block",
"border-radius" = "4px",
"padding-right" = "4px",
"font-weight" = "bold",
"color" = "white",
"order" = x,
"background-color" = csscolor(
colfunc(100)[round(as.numeric(x)*100)]))),
```
And the color remains the same regardless of how many/few packages are loaded.

updated colorization scheme for packages

---

Data/maintenance.txt
Modules/dbupload.R
Server/assessment_criteria.R
Server/db_dash_screen.R
Server/uploadpackage.R
UI/assessment_criteria.R
UI/db_dash_screen.R
UI/uploadpackage.R
Utils/sql_queries/initialize_metric_table.sql
Utils/utils.R
www/main.css

Created a new section on the database view (database icon page) that contains a table and two dropdown inputs to update the weights. This new section is in a new uiOutput so that we can later show it only for authorized users.
Based on todays meeting, these are some of the items we discussed:

Add ui elements to view/change metrics weights

---

Server/db_dash_screen.R
Server/sidebar.R
UI/dashboard_screen.R
Utils/utils.R

Closes #71.
I made my own version of a `shinydashboard::valueBox()` as I found it quite inflexible. I also made sure the color of the `wellPanel()` mimics that which is found on the `db_dash_screen`. Thoughts?

Make Pkg Risk Score more visible

---

Server/assessment_criteria.R
UI/assessment_criteria.R
www/main.css

Closes #72.
Added tab to `assessment criteria` modal regarding how a package receives it's risk calculation. Specifically, click this:
And you'll see this:
Had to dive into some `riskmetric` code to confirm, but it looks good. Unfortunately, the `riskmetric` team didn't spell this out in their documentation, otherwise I'd link to the exported function called [summarize_scores()](https://pharmar.github.io/riskmetric/reference/summarize_scores.html)
Does this look okay? This will be a nice spot for non-admin folks to see what the admin-assigned weights are currently.

Risk calculation info

---

Server/communityusage_metrics.R
Server/maintenance_metrics.R
Server/reportpreview.R
Server/uploadpackage.R
UI/communityusage_metrics.R
UI/maintenance_metrics.R
UI/reportpreview.R
UI/uploadpackage.R
Utils/utils.R
global.R

Closes #127.
I expanded the `introjs` help guide that @marlycormar originally pioneered on the Data Upload tab to include all the tabs, where each tab has it's own `Need Help?` button that runs through all the important objects/inputs on that tab **plus** describes the sidebar inputs **plus** describes some additional buttons that the user should know about (such as the risk criteria modal button & database dashboard button).
I intentionally excluded adding a help button to the database dashboard screen since it's under construction. We can take care of that when the UI elements become more stable like all the other tabs.

Expand help

---

Server/uploadpackage.R

One line of code to close #143. Either of you can review and merge when ready.

Use default `skipLabel` for `rintrojs` guide

---

R/dbupload.R

Uploading package failed due to incorrect variable name.
_Note:_ I took advantage of the PR to rename `package_name` -> `pkg_name` in the function `insert_maintenance_metrics_to_db`, although this instance was not causing any issues.
Fixes issue #184.

Fix package upload

---

R/utils.R

This removes the "No rows were returned" message from `dbSelect()`
It just seems to be cluttering the console.

remove 'no rows were returned' message from dbSelect

---

R/sidebar.R

remove validate() from update package version step.
One thing I noticed was that 
when you select a package and then go and select "-"
the version does not get reset to "-"
This is because of this piece of code in the "update package version" step
```{r, eval=FALSE}
if(input$select_pkg == "-")
validate("Please select a package")
```

sidebar minor update

---

R/sidebar.R

Opens an easily dismissed modal when an overall comment is submitted for the first time and adds reactivity to updating the overall comment so that the report preview will update automatically.

Overall comment feedback

---

app.R

So far I have used a similar approach as @Robert-Krajcik. Instead of using `shinyjs::hide`, I have used a render UI based on if the user was authorized as an administrator. This places the logic for displaying the admin UI in the server logic as opposed to the interface. This keeps users from being able to access the admin tab by editing the HTML or running JavaScript.

Admin mode fixes

---

R/communityMetrics.R
R/dbupload.R
R/uploadPackage.R
R/utils.R

This PR touches 3 files, all to improve the package upload process from a Community Metrics perspective. Specifically:
* Fixes #215. Re-wrote some of `insert_community_metrics_to_db()` so that it could produce results for ~800 packages that have only a single version release (thus meaning, they don't exist on the CRAN Archive for webscraping)
* Added additional 'steps' to progress bar while packages were loading. Previously it was only 1 step per package, now there is like 5 incremental steps per package, giving the user a better idea of load time. I also improved the progress bar messaging slightly.
* Fixes #217
Just need one person to review and merge! Thank you!

Minor Package Upload revamping to improve Community Metrics

---

app.R

This PR addresses #222.
It changes the label text for the modals created by `shinymanager` for creating and editing users.
Additionally it closes the notifications created by `shinymanager` after 1 second (or 1 second after the observe event is triggered). Unfortunately, since these notifications are not named, the solution was to use JS to return a list of all open notifications. At the current moment this does not seem to be an issue,

Improve administrative tools

---

www/reportDocx.Rmd

Closes #212.
Docx Rmarkdown report now ensures there will be a maximum of 9 tick marks no matter how many month of history exist for a certain project. For example: the `stringr` package's plot looks like this:

Docx report's plot for Community Metrics have a readable x-axis

---

R/uploadPackage.R

Implemented a break between the `withProgress()` message and details for prettier output. Same implementation as the metric reweight progress.

Add break between progress message and details

---

.gitignore
R/assessmentInfo.R
R/databaseView.R
R/reportPreview.R
R/reweightView.R
R/sidebar.R
R/uploadPackage.R
R/utils.R
app.R
global.R
www/reportDocx.Rmd
www/reportHtml.Rmd

- Removed `keyring` and related setup.
- Removed `rstudioapi`.
- Disabled package version dropdown (as it is not working and therefore confusing). Add a note to let the user know that the latest package version will be used.
- Added app version.
- Added report metadata: app version, riskmetric version, and metric weights (closes issue #245).
The version released to shinyapps.io lives in the [shinyapps](https://github.com/pharmaR/risk_assessment/tree/shinyapps) branch.

Prep for release

---

.Rbuildignore
DESCRIPTION
NEWS.md
R/_disable_autoload.R
app.R

This is in response to recent Q&A question: https://github.com/pharmaR/risk_assessment/discussions/287
Please review that use case!
I created an app.R file using 'golem::add_rstudioconnect_file()'. Which golem deployment function used isn't very important (there are three). Only downside is it did add pkgload as a new import... not sure how I feel about that.
Related to #289

app.R initiated for deployment for `master` branch

---

README.Rmd
README.md

Let's folks know:
* this is a project sponsored/supported by the R Validation Hub
* there may be additional discussion on slack
The new `README` badge lineup looks like this:

Added new RValHub Slack badge

---

R/utils.R

This is just a one-line fix to remove a warning message coming from two tests.
The fix was to replace a line in function `get_latest_pkg_info()`
from
`colnames(table_infy) <- t(table_infx$X1) %>% dplyr::as_tibble(.name_repair = "minimal") `
to
`colnames(table_infy) <- t(table_infx$X1) %>% as.vector() `
Verification:  run individual tests for `test-dbUpdate` and `test-utils_get_db`

fix warning message generated from get_latest_pkg_info()

---

DESCRIPTION
NEWS.md
R/mod_assessmentInfo.R
R/mod_databaseView.R

Partially closes #383 by including:
* really low hanging fruit of adding an excel/csv download
* cleans up some header inconsistencies from tab to tab
* made 'Explore Metrics' button more compact so that more pkgs can fit on one page, reducing user scroll
* adds search capability so that users can find a package faster

Database Overview: Initial export

---

README.Rmd
README.md

As of today, `riskassesment` is officially featured on https://pharmaverse.org/e2eclinical/validation/ and our badge is being hosted there as well. This PR just adds the badge to the `README` file.
Note: GHAs were failing before this PR and will likely fail again. Let me know when you think it looks kosher, and I can bypass the "branch protections" and merge. Thanks!

Update `README` with pharmaverse badge

---

DESCRIPTION
NEWS.md
R/mod_uploadPackage.R

Added a check for packages being uploaded from the drop-down or read from CSV file.
The message about different versions is given only if the package is read from the CSV file and the version on CRAN is different from the version specified in the CSV file.

Fix the confusing message on pkg upload progress bar (issue #515).

---

R/mod_assessmentInfo.R
R/utils_insert_db.R
inst/db-config.yml
inst/sql_queries/initialize_metric_table.sql

@Jeff-Thompson12, hey I was thinking about adding the top 500 pkgs to the demo version of the app, and thought it'd be a good idea to put in a little workaround to fix for https://github.com/pharmaR/riskmetric/issues/293. What are your thoughts on these changes? Should I clean them up and push them to the `dev` branch as well? The alternative is that we could wait for `{riskmetric}` to solve the bug.
Also, you'll notice I allow tracking of the `database.sql` file on this branch.

Attempted fix for known `riskmetric` weighting bug #293

---

DESCRIPTION
NEWS.md
R/app_server.R
R/mod_uploadPackage.R
R/utils_insert_db.R

A number of functions in `{riskmetric}` run `getOption("repos")`, so to ensure that the correct repo is being used, it needs to be set in the application itself.

Set CRAN repo

---

DESCRIPTION
R/mod_packageDependencies.R

Feature task on the option to hide upload all packages when there is no package to be shown in table #626 
1. Checks if there are packages to be rendered on the table and only shows upload all option when it does

Dependency "Upload All" follow up#626

---

R/app_server.R
R/mod_packageDependencies.R
R/mod_uploadPackage.R
man/packageDependenciesServer.Rd

This PR seeks to improve on the current process in two main ways:
1. Utilizing the `trigger_events` reactive values list
The current process overwrites the list of options for adding a package. It also relies on interactions with the UI when a more direct interaction is possible and probably preferrable.
2. Remove the dependence on the reactive `changes()`
While using `changes()` works, it also causes events to trigger multiple times and other times when unneeded. Also, `changes()` is set to update whenever a decision of overall comment is added to a package. This unnecessarily complicates the reactive graph because neither of those two events are the events desired to being tracked. The reactive is merely changing as a byproduct of the package selection changing. This PR makes the …

Improve uploading packages from dependency tab

---

R/mod_metricBox.R
inst/report_downloads/reportHtml.Rmd

Forces the new lines to be recognized in the cards. Or makes this:
into this:

Force new lines in card paragraphs

---

R/mod_code_explorer_utils.R

The `keep_source` argument in the `parse()` function in base R defaults to `getOption("keep.source")`. This is typically `TRUE` when ran locally but `FALSE` when deployed. The source code is necessary for `utils::getParseData()` to work correctly, so it should be set to `TRUE` in all cases.

Specify `keep_source = TRUE` argument in `parse()`

---

NEWS.md
R/mod_uploadPackage.R
tests/testthat/test-sidebar.R

Ensures users can not create and select packages from CRAN that don't exist

Fix `selectizeInput()` on `Upload Pkgs` tab

---

DESCRIPTION
NEWS.md
R/mod_reweightView.R
tests/testthat/test-reweightView.R

Fix Rescoring/Reweighting Bug

---

DESCRIPTION
NEWS.md
R/mod_code_explorer.R
R/mod_introJS_utils_text.R
R/mod_pkg_explorer.R
man/riskassessment-package.Rd
tests/testthat/test-introJS.R

As per title, tests might be failing, pls have a look

Ni 581 introjshandling

---

DESCRIPTION
NEWS.md
inst/report_downloads/reportHtml.Rmd

Closes #727.
Fixed by copying css from app over to html report. Results:

Sync meter color on HTML reports

---

tests/testthat/test-introJS.R

The day arrived where the test needs to point to the archive instead of available packages

Point tidyr download to archive

---

.github/workflows/R-CMD-check.yaml
.github/workflows/write-manifest.yaml
.rscignore
manifest.json

Run write-manifest on PRs to `dev`

---

DESCRIPTION
NEWS.md
R/mod_uploadPackage.R
R/utils_insert_db.R
man/upload_pkg_lst.Rd
manifest.json

Add user name to batch upload

---

DESCRIPTION
NEWS.md
manifest.json

Prepping for a new minor release

Rel `v3.1.0` Prep

---

DESCRIPTION
NEWS.md
R/mod_packageDependencies.R
R/utils_build_cards.R
R/utils_get_db.R
manifest.json

Bug fix preventing Pkg Deps tab from crashing when dep info not available

---

NEWS.md
R/utils_insert_db.R
manifest.json

Correctly parse `riskmetric` dependency assessment

---

NEWS.md
R/app_server.R
manifest.json

Fix available package list
