pharmaR/riskassessment

.gitignore
Server/uploadpackage.R
risk_assessment.Rproj

This PR contains minor changes:
- Added an RStudio project.
- Added a gitignore file.
- Removed unused class.

Minor changes

---

Server/communityusage_metrics.R

Working towards Remove code duplication #31
Next step might be to replace cum_report.R

remove code duplication in communityusage_metrics

---

Server/sidebar.R
loggit.json

Fix for issue #35 adding comment results in Warning message

Fix sidebar warn msg

---

www/main.css

Before             |  After
:-------------------------:|:-------------------------:

Address minor issue

---

Modules/dbupload.R
Reports/Report_doc.Rmd
Reports/Report_html.Rmd
Server/assessment_criteria.R
Server/testing_metrics.R
Server/tm_report.R
Server/uploadpackage.R
UI/login_screen.R
UI/uploadpackage.R
app.R
global.R
www/main.css

- Remove hard coded paths
- Ignore NAs on the test coverage tab (until this is implemented)
- Minor UI changes on the upload package tab
- Remove default username on the login screen
- Use `global.R` instead of `setup.R`
- Remove package installations from `global.R` (this made the deployment to shinyapps.io fail)

Various fixes

---

Server/assessment_criteria.R
Server/db_dash_screen.R
Server/login_screen.R
UI/assessment_criteria.R
UI/dashboard_screen.R
UI/db_dash_screen.R
Utils/utils.R
app.R
global.R
www/helperScript.js
www/main.css

This PR contains minor changes and a few major ones (described below). I am big opponent of doing generic PRs like this one. However, going through the app as a whole, having been using it for a while, there is space for improvement and standardization.
Major changes
- The db is now created statically before running the app.
- Scripts embedded in the app's code were moved to the helperScript.js file. Also, the scripts called there are only ran after the html page is ready.

General improvements and standardizations

---

Server/communityusage_metrics.R
Server/db_dash_screen.R
Server/maintenance_metrics.R
Server/sidebar.R
Server/testing_metrics.R
Server/uploadpackage.R
Utils/utils.R

Created db function in utils.R to be called any time the db is updated with a newly updated pkg or a new comment is made.
Fixes #84

Ensure db dash updates consistently

---

Modules/dbupload.R
Utils/cum_utils.R
global.R

Remove "all" button from Comm Metrics Graph

---

Reports/Report_doc.Rmd
Reports/Report_html.Rmd
Server/reportpreview.R

Addresses #85 The version of riskmetric doest appear when a report is ran

Add riskmetric version to reportpreview and reports

---

Server/db_dash_screen.R
Server/sidebar.R

This was one of the fixes from the Fixversioning PR

Package Review History remembers the package and version selected

---

UI/dashboard_screen.R

commented out line #29 in dashboard_screen

hide version dropdown on dashboard

---

Reports/Report_doc.Rmd
Reports/Report_html.Rmd
Server/reportpreview.R
UI/dashboard_screen.R
UI/reportpreview.R

test metrics tab removed from dashboard and from report preview

Hide test metrics for now

---

Reports/Report_doc.Rmd
Reports/Report_html.Rmd
Server/reportpreview.R
UI/assessment_criteria.R
UI/dashboard_screen.R
UI/reportpreview.R
app.R

Drop tm panel from dashboard_screen
and remove testing metrics from reportpreview as well as the docx and html reports

Drop tm panel

---

Reports/Report_doc.Rmd
Reports/Report_html.Rmd

Fix report html

---

Server/db_dash_screen.R

Dark Yellow

---

Server/uploadpackage.R
Utils/utils.R

Improve database feedback

---

Utils/utils.R

Change wording when asking for keyring

---

.Rbuildignore
R/sidebar.R
app.R
risk_assessment.Rproj

overall comments yes/edit/no working, final decision working
Addresses issue #168

overall comments yes/edit/no working, final decision working

---

R/introJS.R
R/introJSText.R
R/sidebar.R
Server/uploadpackage.R
UI/communityusage_metrics.R
UI/maintenance_metrics.R
UI/reportpreview.R
UI/uploadpackage.R
app.R

This PR closes #172.
I had to create a couple of div()'s for certain UI's because it was too difficult to peg the UI element name or class. Otherwise, I tried to stick with the existing UI names where possible. I was also able to create a conditional set of steps for the uploadpackages UI, based on whether or not the user had uploaded a csv file (which reveals more UI objects).
A review from just one person will do. Thank you!

Fix introjs guide

---

R/viewComments.R
global.R

Follow up to https://github.com/pharmaR/risk_assessment/pull/203. Created this PR because I couldn't add a commit to that PR.

PR #203 (with call to req and conflict resolved)

---

global.R

Tracked down the source of the error. Simple fix.

Fix error when deselecting package

---

R/databaseView.R

Fixes #223 for `DT` package `v0.21` by adding targets for `columnDefs`.

Update database package table

---

R/addComment.R
R/sidebar.R

Addresses #235. This seemed to be a fairly straightforward fix.

Allow the character "'" in comments

---

R/app_server.R
R/app_ui.R
R/fct_helpers.R
R/introJS.R
R/utils.R

Updated the code base as requested [here](https://github.com/pharmaR/risk_assessment/pull/265#issuecomment-1298752889).
Same procedure as described here:
https://github.com/dreamRs/shinyWidgets/pull/516#issue-1320737774

Switch to Font Awesome 6 icon names

---

DESCRIPTION
NEWS.md
R/databaseView.R
R/reportPreview.R
inst/app/www/.gitignore
inst/app/www/reportPdf.Rmd

Add pdf report option

---

DESCRIPTION
NEWS.md
R/introJSText.R
R/uploadPackage.R

Type Package Names

---

.github/workflows/R-CMD-check-dev.yaml
.github/workflows/R-CMD-check-master.yaml

Does this change look alright? I don't think we need to increment the dev version or include this in the NEWS file.

Adjust GHAs for PRs with `dev` base branch.

---

R/introJSText.R
R/uploadPackage.R
tests/testthat/test-introJS.R

Adds tests for the `introJS` module. Adjustments to the app code has been made where necessary to enable more full testing.

Tests for introJS[UI/Server]

---

DESCRIPTION
R/app_ui.R
inst/app/www/css/main.css

Targets #356 to float the logo to the top right of the application.

Float logo to top right

---

DESCRIPTION
codecov.yml

Disable codecov statuses per [docs](https://docs.codecov.com/docs/commit-status#disabling-a-status).

Disable GHA for codecov/patch & codecov/project

---

R/uploadPackage.R

Addresses two comments by @AARON-CLARK

Rk 366 edits del option

---

NEWS.md
R/utils.R

Minor update to prevent warning message from `test-get_latest_pkg_info.R`

Rk 372 unused connection

---

R/uploadPackage.R

change border color for remove package button to background color

---

tests/testthat/setup.R

Increases shinytest2 timeouts across the board to address #354

Increase shinytest2 timeouts 

---

DESCRIPTION
NEWS.md
inst/WORDLIST
tests/testthat/test-maintenanceMetrics.R

Rk 295 maint metrics

---

DESCRIPTION
NEWS.md
inst/WORDLIST
tests/testthat/test-communityMetrics.R

add test for communityMetrics

---

DESCRIPTION
tests/testthat/test-getTimeStamp.R

Hi @AARON-CLARK, I just added a tolerance to the timestamp check, this should resolve the issue with a test failure.

added tolerance to timestamp check

---

R/global.R
R/reportPreview.R
R/reweightView.R
R/uploadPackage.R
R/utils_insert_db.R
R/utils_startup.R
README.Rmd
README.md
inst/app/www/reportDocx.Rmd
inst/app/www/reportHtml.Rmd
inst/app/www/reportPdf.Rmd
man/app_theme.Rd
man/initialize_raa.Rd
man/riskassessment-package.Rd
tests/testthat/test-utils_get_db.R
tests/testthat/test-utils_insert_db.R
vignettes/Managing_Userids_and_Passwords.Rmd
vignettes/Using_SQLite_Command_Line.Rmd

PR accomplishes two tasks:
* fixes #362 
* fixes #307

Rename function and `riskassessment` pkg name

---

DESCRIPTION
NEWS.md
R/mod_uploadPackage.R

Check URLs used to populate metrics

---

README.Rmd
README.md

Fix R CMD check badge link in README

---

DESCRIPTION
NEWS.md
renv.lock

Increased the R Version on the renv.lock file to 4.2.2

upgraded the RVersion to 4.2.2 in the renv.lock file

---

DESCRIPTION
NEWS.md
README.Rmd
README.md
dev/02_dev.R

Following ["Cutting a new release"](https://github.com/pharmaR/riskassessment/wiki/Cutting-a-new-release) wiki

Prep for `v0.1.1`

---

README.Rmd
README.md

Really small PR fine tuning the wording of the README to accommodate [suggestion ](https://github.com/pharmaverse/pharmaverse/issues/195#issuecomment-1498764813)from pharmaverse maintainers.

Fine tune `README.Rmd` regarding validation scope

---

.github/workflows/R-CMD-check-dev.yaml
.github/workflows/R-CMD-check-master.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml

Update Github Actions

---

DESCRIPTION
R/app_server.R
R/mod_reweightView.R
R/mod_uploadPackage.R
man/reweightViewServer.Rd
man/uploadPackageServer.Rd
tests/testthat/test-apps/reweightView-app/app.R
tests/testthat/test-reweightView.R

Re-weighting Bugs

---

DESCRIPTION
NEWS.md
R/app_server.R

Disable Roles for Editing Multiple Users

---

DESCRIPTION
NEWS.md
R/utils_config_db.R
inst/db-config.yml
tests/testthat/test-utils_config_checkers.R

Resolve Configuration Error

---

renv.lock
renv/activate.R
renv/settings.json

Opening a draft PR to upgrade `renv`.

Upgrade `renv`

---

R/mod_pkg_explorer.R

Fix rendering issue with jsTree

---

DESCRIPTION
NEWS.md
R/mod_databaseView.R

Fix busted 'explore metrics' button on Database tab

---

inst/app/www/css/metric_select.css

Add border back in for package metric select input

---

DESCRIPTION
NEWS.md
R/mod_databaseView.R
R/mod_downloadHandler.R
R/mod_reportPreview.R
R/mod_sidebar.R
inst/report_downloads/reportDocx.Rmd
inst/report_downloads/reportHtml.Rmd
inst/report_downloads/reportPdf.Rmd
tests/testthat/test-databaseView.R

Display date package was added

---

DESCRIPTION
NEWS.md
R/utils_startup.R

Since the database configurations are mostly integrated in the database itself, the application does not need to run all the checkers every single time it is initialized.

Improve App Startup

---

R/app_server.R
R/mod_uploadPackage.R
inst/app/www/css/main.css

Fix CSS for Shiny Notification

---

DESCRIPTION
R/mod_packageDependencies.R
man/riskassessment-package.Rd

Fix dependency metric tab

---

.gitignore
DESCRIPTION
R/mod_downloadHandler.R
R/mod_reportPreview.R
R/utils_get_db.R
inst/report_downloads/reportDocx.Rmd
inst/report_downloads/reportPdf.Rmd

Addresses #741 in part. Does not add tests but seeks to fix current crashes.

Fix application crash

---

DESCRIPTION
R/mod_decision_automation.R
R/mod_decision_automation_utils.R
R/mod_metricBox.R
R/mod_packageDependencies.R
inst/app/www/css/main.css
inst/report_downloads/reportHtml.Rmd
renv.lock
renv/activate.R
tests/testthat/test-code_explorer.R
tests/testthat/test-utils.R

Update R and package versions

---

inst/app/www/css/metric_select.css
inst/app/www/css/modal_elements.css
manifest.json

Recent updates to packages have caused some changes in the layout of elements in the application, in particular the selectize inputs. This PR seeks to repair UI layouts to previous look and feel.

Adjust custom CSS

---

.github/workflows/write-manifest.yaml
R/mod_downloadHandler.R
manifest.json

Addresses a bug in the report inclusions.
To reproduce the bug on the `dev` branch do the following:
1. Select a package.
2. Go to Build Report.
3. Change the report inclusions (e.g. deselect "Report Author")
4. Go to different tab (e.g. Package Metrics)
5. Switch to a different package.
6. Return to Build Report.
7. Observe that your changes in Step 3 are not included

Repair interconnectivity of report inclusions
